### ISSUE TITLE
brew cask install docker no longer works on macOS

### ISSUE THREAD

**Issue by kvignesh1420** [docker-practice/actions-setup-docker#5]
Hi, the docker setup action is erroring out with this error on `macos-latest`:

```
Run docker-practice/actions-setup-docker@v1
install docker
  /usr/local/bin/brew cask install docker
  Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
  Error: Error: The process '/usr/local/bin/brew' failed with exit code 1
```

I guess that this [exec step](https://github.com/docker-practice/actions-setup-docker/blob/330bf23fad1196d9badb2f099414bf5c0a23e1b5/lib/setup-docker.js#L122) might be the issue?

**Comment by khs1994** [comment]
already fixed
