### ISSUE TITLE
Failure on Docker installation!!

### ISSUE THREAD

**Issue by danitseitlin** [docker-practice/actions-setup-docker#7]
/usr/bin/sudo sh -c dpkg -i /tmp/*.deb
  Selecting previously unselected package containerd.io.
  dpkg: regarding .../containerd.io_0.20200914.164213~5b3ac0c-1_amd64.deb containing containerd.io:
   containerd.io conflicts with runc
    moby-runc provides runc and is present and installed.
  
  dpkg: error processing archive /tmp/containerd.io_0.20200914.164213~5b3ac0c-1_amd64.deb (--install):
   conflicting packages - not installing containerd.io
  (Reading database ... 283207 files and directories currently installed.)
  Preparing to unpack .../libseccomp2_2.4.4-1~bpo10+1_amd64.deb ...
  Unpacking libseccomp2:amd64 (2.4.4-1~bpo10+1) over (2.4.3-1ubuntu3.18.04.3) ...
  Selecting previously unselected package moby-snapshot-cli.
  Preparing to unpack .../moby-snapshot-cli_0.0.0-20200914120255-e0eba83-0~ubuntu-focal_amd64.deb ...
  Unpacking moby-snapshot-cli (5:0.0.0-20200914120255-e0eba83-0~ubuntu-focal) ...
  Selecting previously unselected package moby-snapshot-rootless-extras.
  Preparing to unpack .../moby-snapshot-rootless-extras_0.0.0-20200914120255-e0eba83-0~ubuntu-focal_amd64.deb ...
  Unpacking moby-snapshot-rootless-extras (5:0.0.0-20200914120255-e0eba83-0~ubuntu-focal) ...
  Selecting previously unselected package moby-snapshot.
  Preparing to unpack .../moby-snapshot_0.0.0-20200914120255-e0eba83-0~ubuntu-focal_amd64.deb ...
  Unpacking moby-snapshot (5:0.0.0-20200914120255-e0eba83-0~ubuntu-focal) ...
  Setting up libseccomp2:amd64 (2.4.4-1~bpo10+1) ...
  Setting up moby-snapshot-cli (5:0.0.0-20200914120255-e0eba83-0~ubuntu-focal) ...
  dpkg: dependency problems prevent configuration of moby-snapshot:
   moby-snapshot depends on containerd.io; however:
    Package containerd.io is not installed.
    Package moby-containerd which provides containerd.io is not installed.
  
  dpkg: error processing package moby-snapshot (--install):
   dependency problems - leaving unconfigured
  dpkg: dependency problems prevent configuration of moby-snapshot-rootless-extras:
   moby-snapshot-rootless-extras depends on moby-snapshot; however:
    Package moby-snapshot is not configured yet.
  
  dpkg: error processing package moby-snapshot-rootless-extras (--install):
   dependency problems - leaving unconfigured
  Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
  Errors were encountered while processing:
   /tmp/containerd.io_0.20200914.164213~5b3ac0c-1_amd64.deb
   moby-snapshot
   moby-snapshot-rootless-extras
  Error: Error: The process '/usr/bin/sudo' failed with exit code 1

REF: https://github.com/danitseitlin/redis-modules-sdk/pull/44/checks?check_run_id=1893336254

**Comment by danitseitlin** [comment]
The Cis are still broken

**Comment by khs1994** [comment]
already fixed
